version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # AWS edge (S3/STS/IAM/KMS)
    environment:
      - SERVICES=s3,sts,iam,kms
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4566/health || curl -fsS http://localhost:4566/_localstack/health"]
      interval: 3s
      timeout: 2s
      retries: 60
    volumes:
      - localstack-data:/var/lib/localstack
      - ./localstack-init/ready.d:/etc/localstack/init/ready.d:ro

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      # Listeners inside the container
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      # What clients should dial from the host
      - --advertise-kafka-addr=internal://redpanda:9092,external://127.0.0.1:19092
      - --advertise-rpc-addr=redpanda:33145
    ports:
      - "19092:19092" # Host bootstrap => 127.0.0.1:19092
      - "9644:9644"   # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9644/v1/status/ready"]
      interval: 5s
      timeout: 3s
      retries: 60

  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"  # http://localhost:8080

  rpk:
    image: redpandadata/redpanda:latest
    container_name: rpk
    entrypoint: ["sh","-c","tail -f /dev/null"]
    restart: unless-stopped
    depends_on:
      redpanda:
        condition: service_healthy

  kcat:
    image: edenhill/kcat:1.7.1
    container_name: kcat
    entrypoint: ["sh","-c","tail -f /dev/null"]
    restart: unless-stopped
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  localstack-data:
  redpanda-data:
