package meter

import "github.com/joeydtaylor/electrician/pkg/internal/types"

var percentageMetrics = map[string]struct{}{
	types.MetricCurrentCpuPercentage:                         {},
	types.MetricCurrentRamPercentage:                         {},
	types.MetricTransformPercentage:                          {},
	types.MetricErrorPercentage:                              {},
	types.MetricProgressPercentage:                           {},
	types.MetricTransformationErrorPercentage:                {},
	types.MetricSurgeProtectorBackupWireSubmissionPercentage: {},
}

var metricDisplayNames = map[string]string{
	types.MetricCurrentCpuPercentage:                         "Current CPU",
	types.MetricCurrentRamPercentage:                         "Current RAM",
	types.MetricPeakGoRoutinesActive:                         "Peak Go Routines Active",
	types.MetricCurrentGoRoutinesActive:                      "Current Go Routines Active",
	types.MetricPeakProcessedPerSecond:                       "Peak Processed Per Second",
	types.MetricPeakTransformedPerSecond:                     "Peak Transformed Per Second",
	types.MetricPeakTransformationErrorsPerSecond:            "Maximum Error Per Second",
	types.MetricProcessedPerSecond:                           "Processed Per Second",
	types.MetricTransformationErrorsPerSecond:                "Transformation Errors Per Second",
	types.MetricTransformsPerSecond:                          "Transforms Per Second",
	types.MetricTotalPendingCount:                            "Total Pending Items",
	types.MetricTotalComponentsUsedCount:                     "Total Components Used",
	types.MetricSurgeProtectorCurrentTripCount:               "Active Tripped Surge Protectors",
	types.MetricTransformationErrorPercentage:                "Total Transform Error Percentage",
	types.MetricTransformPercentage:                          "Total Transform Success Percentage",
	types.MetricErrorPercentage:                              "Total Error Percentage",
	types.MetricTotalErrorCount:                              "Total Error Count",
	types.MetricProgressPercentage:                           "Progress",
	types.MetricTotalProcessedCount:                          "Total Items Processed",
	types.MetricTotalSubmittedCount:                          "Total Items Submitted",
	types.MetricTotalTransformedCount:                        "Total Items Transformed",
	types.MetricMeterConnectedComponentCount:                 "Meter Connected Components",
	types.MetricComponentRunningCount:                        "Active Components",
	types.MetricLoggerConnectedComponentCount:                "Logger Connected Components",
	types.MetricComponentRestartCount:                        "Component Restarts",
	types.MetricComponentLifecycleErrorCount:                 "Component Lifecycle Errors",
	types.MetricWireElementTransformCount:                    "Wire Transform Operations",
	types.MetricWireElementTransformErrorCount:               "Wire Transform Errors",
	types.MetricWireRunningCount:                             "Wires Currently Active",
	types.MetricWireElementSubmitCount:                       "Items Submitted via Wire",
	types.MetricWireElementSubmitErrorCount:                  "Wire Submission Errors",
	types.MetricWireElementSubmitCancelCount:                 "Wire Submission Cancellations",
	types.MetricWireElementCancelCount:                       "Wire Cancellations",
	types.MetricWireElementErrorCount:                        "Wire Processing Errors",
	types.MetricWireElementRecoverAttemptCount:               "Wire Recovery Attempts",
	types.MetricWireElementRecoverSuccessCount:               "Successful Wire Recoveries",
	types.MetricWireElementRecoverFailureCount:               "Failed Wire Recoveries",
	types.MetricCircuitBreakerResetTimer:                     "Circuit Breaker Reset Timer",
	types.MetricCircuitBreakerLastTripTime:                   "Circuit Breaker Last Trip Time",
	types.MetricCircuitBreakerLastErrorRecordTime:            "Circuit Breaker Last Recorded Error Time",
	types.MetricCircuitBreakerLastResetTime:                  "Circuit Breaker Last Reset Time",
	types.MetricCircuitBreakerNextResetTime:                  "Circuit Breaker Next Reset Time",
	types.MetricCircuitBreakerCurrentTripCount:               "Current Tripped Circuit Breakers",
	types.MetricCircuitBreakerTripCount:                      "Total Circuit Breaker Trips",
	types.MetricCircuitBreakerResetCount:                     "Circuit Breaker Resets",
	types.MetricCircuitBreakerNeutralWireSubmissionCount:     "Elements Diverted by Circuit Breaker",
	types.MetricCircuitBreakerRecordedErrorCount:             "Errors Recorded by Circuit Breaker",
	types.MetricCircuitBreakerDroppedElementCount:            "Elements Dropped by Circuit Breaker",
	types.MetricCircuitBreakerNeutralWireConnectedCount:      "Ground Wires Running",
	types.MetricCircuitBreakerNeutralWireFailureCount:        "Ground Wire Failures",
	types.MetricCircuitBreakerCount:                          "Circuit Breaker Count",
	types.MetricHTTPRequestMadeCount:                         "HTTP Requests Made",
	types.MetricHTTPRequestReceivedCount:                     "HTTP Requests Received",
	types.MetricHTTPRequestCompletedCount:                    "HTTP Requests Completed",
	types.MetricHTTPResponseCount:                            "HTTP Responses",
	types.MetricHTTPClientErrorCount:                         "HTTP Client Errors",
	types.MetricHTTPClientRetryCount:                         "HTTP Client Retries",
	types.MetricHTTPOAuth2ClientCount:                        "OAuth2 Clients Active",
	types.MetricHTTPResponseErrorCount:                       "HTTP Response Errors",
	types.MetricHTTPClientWithTlsPinningCount:                "HTTP Clients with TLS Pinning",
	types.MetricHTTPClientFetchCount:                         "HTTP Client Fetch Operations",
	types.MetricHTTPClientFetchErrorCount:                    "HTTP Client Fetch Errors",
	types.MetricHTTPClientFetchAndSubmitErrorCount:           "HTTP Fetch and Submit Errors",
	types.MetricHTTPClientWithActiveOAuthTokenCount:          "Active OAuth Tokens",
	types.MetricHTTPClientOAuthTokenRequestCount:             "OAuth Token Requests",
	types.MetricHTTPClientOAuthTokenErrorCount:               "OAuth Token Errors",
	types.MetricHTTPClientJsonUnmarshalErrorCount:            "JSON Unmarshalling Errors",
	types.MetricHTTPClientSuccessfulFetchCount:               "Successful HTTP Fetches",
	types.MetricHTTPClientRetryExhaustedCount:                "HTTP Retries Exhausted",
	types.MetricSurgeProtectorBackupWireSubmissionCount:      "Surge Protector Backup Wire Submissions",
	types.MetricSurgeProtectorBackupWireSubmissionPercentage: "Surge Protector Backup Wire Percentage",
	types.MetricSurgeProtectorAttachedCount:                  "Surge Protectors Attached",
	types.MetricSurgeProtectorDropCount:                      "Surge Protector Drops",
	types.MetricSurgeCount:                                   "Surge Protector Count",
	types.MetricSurgeTripCount:                               "Surge Protector Trips",
	types.MetricSurgeResetCount:                              "Surge Protector Resets",
	types.MetricSurgeBackupFailureCount:                      "Surge Protector Backup Failures",
	types.MetricSurgeRateLimitExceedCount:                    "Surge Rate Limit Exceedances",
	types.MetricSurgeBlackoutTripCount:                       "Surge Blackout Trips",
	types.MetricSurgeBlackoutResetCount:                      "Surge Blackout Resets",
	types.MetricResisterConnectedCount:                       "Resisters Connected",
	types.MetricResisterClearedCount:                         "Resister Clears",
	types.MetricResisterElementRequeued:                      "Resister Elements Requeued",
	types.MetricResisterElementQueuedCount:                   "Resister Total Queued Count",
	types.MetricResisterElementCurrentlyQueuedCount:          "Resister Currently Queued",
	types.MetricResisterElementDequeued:                      "Resister Elements Dequeued",
	types.MetricReceivingRelayListeningCount:                 "Relays Currently Listening",
	types.MetricReceivingRelayRunningCount:                   "Relays Currently Running",
	types.MetricReceivingRelayReceivedCount:                  "Relays Received Count",
	types.MetricReceivingRelayUnwrappedPayloadCount:          "Relays Unwrapped Payloads",
	types.MetricReceivingRelayRelayedCount:                   "Relays Relayed Messages",
	types.MetricReceivingRelayUnwrappedPayloadErrorCount:     "Relays Payload Unwrap Errors",
	types.MetricReceivingRelayStreamReceiveCount:             "Relays Stream Received",
	types.MetricReceivingRelayTargetCount:                    "Relay Targets Count",
	types.MetricReceivingRelayErrorCount:                     "Relay Errors",
	types.MetricReceivingRelayNoTLSCount:                     "Relays without TLS",
	types.MetricProcessDuration:                              "Process Duration",
	types.MetricGeneratorRunningCount:                        "Generators Currently Active",
	types.MetricGeneratorSubmitCount:                         "Generator Submissions",
	types.MetricGeneratorSubmitErrorCount:                    "Generator Submission Errors",
	types.MetricForwardRelaySubmitErrorCount:                 "Forward Relay Submission Errors",
	types.MetricForwardRelaySubmitCount:                      "Forward Relay Submissions",
	types.MetricForwardRelayRelayedCount:                     "Forward Relay Relayed Messages",
	types.MetricForwardRelayWithPerformanceOptionCount:       "Forward Relays with Performance Options",
	types.MetricForwardRelayWithTlsConfigCount:               "Forward Relays with TLS Configuration",
	types.MetricForwardRelayRunningCount:                     "Forward Relays Running",
	types.MetricForwardRelayErrorCount:                       "Forward Relay Errors",
	types.MetricForwardRelayPayloadCompressionCount:          "Payload Compressions",
	types.MetricForwardRelayPayloadCompressionErrorCount:     "Payload Compression Errors",
	types.MetricForwardRelayWrappedPayloadCount:              "Wrapped Payloads",
	types.MetricForwardRelayInputCount:                       "Forward Relay Inputs",
	types.MetricConduitRunningCount:                          "Conduits Running",
}

var defaultMetricNames = []string{
	types.MetricTransformsPerSecond,
	types.MetricTransformationErrorsPerSecond,
	types.MetricTotalErrorCount,
	types.MetricTransformPercentage,
	types.MetricErrorPercentage,
	types.MetricProgressPercentage,
	types.MetricTotalProcessedCount,
	types.MetricTotalSubmittedCount,
	types.MetricTotalTransformedCount,
	types.MetricMeterConnectedComponentCount,
	types.MetricComponentRunningCount,
	types.MetricLoggerConnectedComponentCount,
	types.MetricComponentRestartCount,
	types.MetricComponentLifecycleErrorCount,
	types.MetricWireElementTransformCount,
	types.MetricWireElementTransformErrorCount,
	types.MetricWireRunningCount,
	types.MetricWireElementSubmitCount,
	types.MetricWireElementSubmitErrorCount,
	types.MetricWireElementSubmitCancelCount,
	types.MetricWireElementCancelCount,
	types.MetricWireElementErrorCount,
	types.MetricWireElementRecoverAttemptCount,
	types.MetricWireElementRecoverSuccessCount,
	types.MetricWireElementRecoverFailureCount,
	types.MetricCircuitBreakerResetTimer,
	types.MetricCircuitBreakerLastErrorRecordTime,
	types.MetricCircuitBreakerLastResetTime,
	types.MetricCircuitBreakerNextResetTime,
	types.MetricCircuitBreakerCurrentTripCount,
	types.MetricCircuitBreakerTripCount,
	types.MetricCircuitBreakerResetCount,
	types.MetricCircuitBreakerNeutralWireSubmissionCount,
	types.MetricCircuitBreakerRecordedErrorCount,
	types.MetricCircuitBreakerDroppedElementCount,
	types.MetricCircuitBreakerNeutralWireConnectedCount,
	types.MetricCircuitBreakerNeutralWireFailureCount,
	types.MetricCircuitBreakerCount,
	types.MetricTransformationErrorPercentage,
	types.MetricHTTPRequestMadeCount,
	types.MetricHTTPRequestReceivedCount,
	types.MetricHTTPRequestCompletedCount,
	types.MetricHTTPResponseCount,
	types.MetricHTTPClientErrorCount,
	types.MetricHTTPClientRetryCount,
	types.MetricHTTPOAuth2ClientCount,
	types.MetricHTTPResponseErrorCount,
	types.MetricHTTPClientWithTlsPinningCount,
	types.MetricHTTPClientFetchCount,
	types.MetricHTTPClientFetchErrorCount,
	types.MetricHTTPClientFetchAndSubmitErrorCount,
	types.MetricHTTPClientWithActiveOAuthTokenCount,
	types.MetricHTTPClientOAuthTokenRequestCount,
	types.MetricHTTPClientOAuthTokenErrorCount,
	types.MetricHTTPClientJsonUnmarshalErrorCount,
	types.MetricHTTPClientSuccessfulFetchCount,
	types.MetricHTTPClientRetryExhaustedCount,
	types.MetricSurgeProtectorBackupWireSubmissionCount,
	types.MetricSurgeProtectorBackupWireSubmissionPercentage,
	types.MetricSurgeProtectorAttachedCount,
	types.MetricSurgeProtectorDropCount,
	types.MetricSurgeCount,
	types.MetricSurgeProtectorCurrentTripCount,
	types.MetricSurgeTripCount,
	types.MetricSurgeResetCount,
	types.MetricSurgeBackupFailureCount,
	types.MetricSurgeRateLimitExceedCount,
	types.MetricSurgeBlackoutTripCount,
	types.MetricSurgeBlackoutResetCount,
	types.MetricResisterConnectedCount,
	types.MetricResisterClearedCount,
	types.MetricResisterElementRequeued,
	types.MetricResisterElementQueuedCount,
	types.MetricResisterElementCurrentlyQueuedCount,
	types.MetricResisterElementDequeued,
	types.MetricReceivingRelayListeningCount,
	types.MetricReceivingRelayRunningCount,
	types.MetricReceivingRelayReceivedCount,
	types.MetricReceivingRelayUnwrappedPayloadCount,
	types.MetricReceivingRelayRelayedCount,
	types.MetricReceivingRelayUnwrappedPayloadErrorCount,
	types.MetricReceivingRelayStreamReceiveCount,
	types.MetricReceivingRelayTargetCount,
	types.MetricReceivingRelayErrorCount,
	types.MetricReceivingRelayNoTLSCount,
	types.MetricProcessDuration,
	types.MetricGeneratorRunningCount,
	types.MetricGeneratorSubmitCount,
	types.MetricGeneratorSubmitErrorCount,
	types.MetricForwardRelaySubmitErrorCount,
	types.MetricForwardRelaySubmitCount,
	types.MetricForwardRelayRelayedCount,
	types.MetricForwardRelayWithPerformanceOptionCount,
	types.MetricForwardRelayWithTlsConfigCount,
	types.MetricForwardRelayRunningCount,
	types.MetricForwardRelayErrorCount,
	types.MetricForwardRelayPayloadCompressionCount,
	types.MetricForwardRelayPayloadCompressionErrorCount,
	types.MetricForwardRelayWrappedPayloadCount,
	types.MetricForwardRelayInputCount,
	types.MetricConduitRunningCount,
}
